name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # Adjust according to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '20'  # Ensure it matches your project's requirements

      - name: Build and Deploy
        run: |
          echo "Building and deploying to GitHub Pages..."
          mkdir -p public
          cp -r * public/
          touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
