name: GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Update to v4
        with:
          node-version: '20'  # Explicitly set to Node.js 20

      - name: Build and Deploy
        run: |
          echo "Building and deploying to GitHub Pages..."
          mkdir -p public
          cp -r * public/
          touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
